package com.proyecto2.UI.CreandoTablero;

import com.proyecto2.Entidad.Jugador;
import com.proyecto2.Entidad.UI.JugadorUI;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class AgregarJugadores extends javax.swing.JFrame {

    private Jugador[] jugadores;
    private JugadorUI[] jugadoresUI;

    /**
     * Le envíamo de parámetro lo que contengga el spiner de cantidad jugadores
     *
     * @param cantidadJugadores
     */
    public AgregarJugadores(int cantidadJugadores) {
        initComponents();
        jugadores = new Jugador[cantidadJugadores];
        jugadoresUI = new JugadorUI[cantidadJugadores];
        agregarJugadores();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIngresJugadore = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGuardarJugadores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelIngresJugadoreLayout = new javax.swing.GroupLayout(panelIngresJugadore);
        panelIngresJugadore.setLayout(panelIngresJugadoreLayout);
        panelIngresJugadoreLayout.setHorizontalGroup(
            panelIngresJugadoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelIngresJugadoreLayout.setVerticalGroup(
            panelIngresJugadoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jLabel1.setText("Ingrese el nombre de los jugadores: ");

        btnGuardarJugadores.setText("Guadar");
        btnGuardarJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarJugadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
            .addComponent(panelIngresJugadore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardarJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(panelIngresJugadore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarJugadores))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarJugadoresActionPerformed
        for (int i = 0; i < jugadores.length; i++) {
            if (jugadoresUI[i].getTxtNombres().getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor complete los campos en blanco");
            } else if (jugadoresUI[i].getTxtNombres().getText() != null) {
                break;
            }
        }
        this.setVisible(false);

    }//GEN-LAST:event_btnGuardarJugadoresActionPerformed

    public void agregarJugadores() {
        for (int i = 0; i < jugadores.length; i++) {
            JugadorUI jugadorUI = new JugadorUI(i);
            panelIngresJugadore.add(jugadorUI.getLabelNombre());
            panelIngresJugadore.add(jugadorUI.getTxtNombres());
            jugadorUI.setBounds(i);
            jugadoresUI[i] = jugadorUI;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarJugadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelIngresJugadore;
    // End of variables declaration//GEN-END:variables
}
