package com.proyecto2.UI.CreandoTablero;

/**
 *
 * @author Luis
 */
public class CasillaTrampaUI extends javax.swing.JFrame {

    /**
     * Creates new form CasillaTrampa
     */
    public CasillaTrampaUI() {
        initComponents();
        btnGroup.add(this.radBtPagarmulta);
        btnGroup.add(this.radBtPerderturno);
        btnGroup.add(this.rdBtCambiocasilla);
        spinerCambiocasilla.setEnabled(false);
        spinerPagarmulta.setEnabled(false);
        spinerPerderTurno.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdBtCambiocasilla = new javax.swing.JRadioButton();
        radBtPerderturno = new javax.swing.JRadioButton();
        radBtPagarmulta = new javax.swing.JRadioButton();
        spinerCambiocasilla = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spinerPerderTurno = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spinerPagarmulta = new javax.swing.JSpinner();
        btnTrampaAcptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rdBtCambiocasilla.setText("Cambiar de casilla");
        rdBtCambiocasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtCambiocasillaActionPerformed(evt);
            }
        });

        radBtPerderturno.setText("Perder turno");
        radBtPerderturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtPerderturnoActionPerformed(evt);
            }
        });

        radBtPagarmulta.setText("Pagar multa");
        radBtPagarmulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtPagarmultaActionPerformed(evt);
            }
        });

        spinerCambiocasilla.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel1.setText("Ingrese la cantidad de casillas a moverse");

        jLabel2.setText("Cantidad de turnos a perder");

        spinerPerderTurno.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel3.setText("Cantidad a pagar : ");

        spinerPagarmulta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btnTrampaAcptar.setText("Aceptar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radBtPagarmulta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(radBtPerderturno, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rdBtCambiocasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTrampaAcptar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spinerCambiocasilla, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(spinerPerderTurno)
                            .addComponent(spinerPagarmulta))))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtCambiocasilla)
                    .addComponent(jLabel1)
                    .addComponent(spinerCambiocasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBtPerderturno)
                    .addComponent(jLabel2)
                    .addComponent(spinerPerderTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBtPagarmulta)
                    .addComponent(jLabel3)
                    .addComponent(spinerPagarmulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTrampaAcptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radBtPagarmultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtPagarmultaActionPerformed
        spinerPagarmulta.setEnabled(true);
        spinerCambiocasilla.setEnabled(false);
        spinerPerderTurno.setEnabled(false);
    }//GEN-LAST:event_radBtPagarmultaActionPerformed

    private void rdBtCambiocasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtCambiocasillaActionPerformed
        spinerCambiocasilla.setEnabled(true);
        spinerPagarmulta.setEnabled(false);
        spinerPerderTurno.setEnabled(false);
    }//GEN-LAST:event_rdBtCambiocasillaActionPerformed

    private void radBtPerderturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtPerderturnoActionPerformed
        spinerPerderTurno.setEnabled(true);
        spinerCambiocasilla.setEnabled(false);
        spinerPagarmulta.setEnabled(false);
    }//GEN-LAST:event_radBtPerderturnoActionPerformed
    public void ActionPerformed(java.awt.event.ActionEvent e) {
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CasillaTrampaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CasillaTrampaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CasillaTrampaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CasillaTrampaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasillaTrampaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnTrampaAcptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radBtPagarmulta;
    private javax.swing.JRadioButton radBtPerderturno;
    private javax.swing.JRadioButton rdBtCambiocasilla;
    private javax.swing.JSpinner spinerCambiocasilla;
    private javax.swing.JSpinner spinerPagarmulta;
    private javax.swing.JSpinner spinerPerderTurno;
    // End of variables declaration//GEN-END:variables

}
