package com.proyecto2.UI.CreandoTablero;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Luis
 */
public class CasillaUI extends javax.swing.JPanel {

    /**
     * Creates new form Casilla
     */
    public CasillaUI(int posX, int posY, int ancho, int alto) {
        initComponents();
        setBounds(posX, posY, ancho, alto);
        //establcemos el color del label
        labelNombreCasilla.setOpaque(true);
        labelNombreCasilla.setBackground(Color.LIGHT_GRAY);
        labelCostoEstancia.setOpaque(true);
        labelCostoEstancia.setBackground(Color.LIGHT_GRAY);

        setBackground(Color.LIGHT_GRAY);//color del panel
        labelNombreCasilla.setText(" ");
        labelCostoEstancia.setText(" ");
        //
    }

    public CasillaUI() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombreCasilla = new javax.swing.JLabel();
        labelCostoEstancia = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreCasilla, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
            .addComponent(labelCostoEstancia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelNombreCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCostoEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLabelCostoEstancia() {
        return labelCostoEstancia;
    }

    public JLabel getLabelNombreCasilla() {
        return labelNombreCasilla;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelCostoEstancia;
    private javax.swing.JLabel labelNombreCasilla;
    // End of variables declaration//GEN-END:variables

}
