package com.proyecto2.UI.CreandoTablero;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Luis
 */
public class PedirTipoCasilla extends javax.swing.JFrame {

    private CasillaUI casillaui;
    private CasillaTrampaUI trampa;

    /**
     * Creates new form PedirTipoCasilla
     */
    public PedirTipoCasilla() {

        initComponents();
        casillaui = new CasillaUI();
        setTitle("ElecciOn de tipo de casilla");
        trampa = new CasillaTrampaUI();
        radBtnINICIO.setActionCommand(radBtnINICIO.getText());
        radioBtnCarcel.setActionCommand(radioBtnCarcel.getText());
        radioBtnNEUTRO.setActionCommand(radioBtnNEUTRO.getText());
        radioBtnPROPIEDAD.setActionCommand(radioBtnPROPIEDAD.getText());
        radioBtnTRAMPA.setActionCommand(radioBtnTRAMPA.getText());
        radioBtnTomaTarjeta.setActionCommand(radioBtnTomaTarjeta.getText());
        //se agrega los radioBtn a un grupo
        grupoRadioBoton.add(this.radBtnINICIO);
        grupoRadioBoton.add(this.radioBtnNEUTRO);
        grupoRadioBoton.add(this.radioBtnTRAMPA);
        grupoRadioBoton.add(this.radioBtnPROPIEDAD);
        grupoRadioBoton.add(this.radioBtnTomaTarjeta);
        grupoRadioBoton.add(this.radioBtnCarcel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadioBoton = new javax.swing.ButtonGroup();
        panelSeleccionCasilla = new javax.swing.JPanel();
        radBtnINICIO = new javax.swing.JRadioButton();
        radioBtnNEUTRO = new javax.swing.JRadioButton();
        radioBtnTRAMPA = new javax.swing.JRadioButton();
        radioBtnPROPIEDAD = new javax.swing.JRadioButton();
        radioBtnTomaTarjeta = new javax.swing.JRadioButton();
        radioBtnCarcel = new javax.swing.JRadioButton();
        botonGuardar = new javax.swing.JButton();
        etiqueta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSeleccionCasilla.setBackground(new java.awt.Color(255, 153, 51));

        radBtnINICIO.setBackground(new java.awt.Color(102, 102, 255));
        radBtnINICIO.setText("Inicio");
        radBtnINICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnINICIOActionPerformed(evt);
            }
        });

        radioBtnNEUTRO.setBackground(new java.awt.Color(102, 102, 255));
        radioBtnNEUTRO.setText("Neutro");
        radioBtnNEUTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnNEUTROActionPerformed(evt);
            }
        });

        radioBtnTRAMPA.setBackground(new java.awt.Color(102, 102, 255));
        radioBtnTRAMPA.setText("Trampa");
        radioBtnTRAMPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnTRAMPAActionPerformed(evt);
            }
        });

        radioBtnPROPIEDAD.setBackground(new java.awt.Color(102, 102, 255));
        radioBtnPROPIEDAD.setText("Propiedad");
        radioBtnPROPIEDAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPROPIEDADActionPerformed(evt);
            }
        });

        radioBtnTomaTarjeta.setBackground(new java.awt.Color(102, 102, 255));
        radioBtnTomaTarjeta.setText("Toma una tarjeta");
        radioBtnTomaTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnTomaTarjetaActionPerformed(evt);
            }
        });

        radioBtnCarcel.setBackground(new java.awt.Color(102, 102, 255));
        radioBtnCarcel.setText("Cárcel");
        radioBtnCarcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnCarcelActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(102, 102, 102));
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        etiqueta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        etiqueta.setForeground(new java.awt.Color(0, 0, 0));
        etiqueta.setText("Escoge el tipo de casilla quieres colocar");

        javax.swing.GroupLayout panelSeleccionCasillaLayout = new javax.swing.GroupLayout(panelSeleccionCasilla);
        panelSeleccionCasilla.setLayout(panelSeleccionCasillaLayout);
        panelSeleccionCasillaLayout.setHorizontalGroup(
            panelSeleccionCasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionCasillaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelSeleccionCasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSeleccionCasillaLayout.createSequentialGroup()
                        .addComponent(etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionCasillaLayout.createSequentialGroup()
                        .addGroup(panelSeleccionCasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radBtnINICIO, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioBtnPROPIEDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioBtnTRAMPA, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioBtnNEUTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelSeleccionCasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSeleccionCasillaLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(panelSeleccionCasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelSeleccionCasillaLayout.createSequentialGroup()
                                        .addComponent(radioBtnCarcel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(radioBtnTomaTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                            .addGroup(panelSeleccionCasillaLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(27, 27, 27))))
        );
        panelSeleccionCasillaLayout.setVerticalGroup(
            panelSeleccionCasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionCasillaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(etiqueta)
                .addGap(18, 41, Short.MAX_VALUE)
                .addGroup(panelSeleccionCasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radBtnINICIO, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioBtnTomaTarjeta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSeleccionCasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBtnNEUTRO)
                    .addComponent(radioBtnCarcel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBtnTRAMPA)
                .addGap(5, 5, 5)
                .addGroup(panelSeleccionCasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(radioBtnPROPIEDAD))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelSeleccionCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSeleccionCasilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radBtnINICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnINICIOActionPerformed

    }//GEN-LAST:event_radBtnINICIOActionPerformed

    private void radioBtnNEUTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnNEUTROActionPerformed

    }//GEN-LAST:event_radioBtnNEUTROActionPerformed

    private void radioBtnTRAMPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnTRAMPAActionPerformed

        trampa.setVisible(true);
    }//GEN-LAST:event_radioBtnTRAMPAActionPerformed

    private void radioBtnPROPIEDADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPROPIEDADActionPerformed

    }//GEN-LAST:event_radioBtnPROPIEDADActionPerformed

    private void radioBtnTomaTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnTomaTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnTomaTarjetaActionPerformed

    private void radioBtnCarcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnCarcelActionPerformed

        System.out.println(radioBotonSeleccionado());

    }//GEN-LAST:event_radioBtnCarcelActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed

    }//GEN-LAST:event_botonGuardarActionPerformed
    public void botonGUARDARmouseClicked(java.awt.event.MouseEvent e, CasillaUI casilla) {
       
    }

    public String radioBotonSeleccionado() {
        ButtonModel boton = grupoRadioBoton.getSelection();
        String seleccionadoNombre = boton.getActionCommand();
        return seleccionadoNombre;
    }

    public JButton getBotonGuardar() {
        return botonGuardar;
    }

    public ButtonGroup getGrupoRadioBoton() {
        return grupoRadioBoton;
    }

    public JRadioButton getRadBtnINICIO() {
        return radBtnINICIO;
    }

    public JRadioButton getRadioBtnCarcel() {
        return radioBtnCarcel;
    }

    public JRadioButton getRadioBtnNEUTRO() {
        return radioBtnNEUTRO;
    }

    public JRadioButton getRadioBtnPROPIEDAD() {
        return radioBtnPROPIEDAD;
    }

    public JRadioButton getRadioBtnTomaTarjeta() {
        return radioBtnTomaTarjeta;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedirTipoCasilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedirTipoCasilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedirTipoCasilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedirTipoCasilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedirTipoCasilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JLabel etiqueta;
    private javax.swing.ButtonGroup grupoRadioBoton;
    private javax.swing.JPanel panelSeleccionCasilla;
    private javax.swing.JRadioButton radBtnINICIO;
    private javax.swing.JRadioButton radioBtnCarcel;
    private javax.swing.JRadioButton radioBtnNEUTRO;
    private javax.swing.JRadioButton radioBtnPROPIEDAD;
    private javax.swing.JRadioButton radioBtnTRAMPA;
    private javax.swing.JRadioButton radioBtnTomaTarjeta;
    // End of variables declaration//GEN-END:variables
}
