package com.proyecto2.UI;

import com.proyecto2.CosasUtiles.MetodosUtiles;
import com.proyecto2.Entidad.Temporizador;
import com.proyecto2.Jugar.Juego;
import com.proyecto2.Manejadores.ManejadorDado;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import com.proyecto2.UI.*;

/**
 *
 * @author Luis
 */
public class JuegoPrincipal extends javax.swing.JFrame implements ActionListener {

    private boolean iniciarTarea; //para que inicie el temporizador/cronometro
    private boolean corriendoTemp;
    private Temporizador temporizador;
    //JUEGO
    private Juego juego;

    /**
     * Creates new form JuegoPrincipal
     */
    public JuegoPrincipal() {
        this.iniciarTarea = true;
        this.corriendoTemp = false;
        juego = new Juego();
        initComponents();
        setTitle("Jugando");
        btnIniciarTemp.addActionListener(this);
        btnPausarTemp.addActionListener(this);
        //más componentes
        agregarIconoDados();
        agregarCasillas();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        labelTempTitulo = new javax.swing.JLabel();
        labelTemporizador = new javax.swing.JLabel();
        btnPausarTemp = new javax.swing.JButton();
        btnIniciarTemp = new javax.swing.JButton();
        spinerHoras = new javax.swing.JSpinner();
        spinerMinutos = new javax.swing.JSpinner();
        horas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelDado2 = new javax.swing.JLabel();
        labelDado3 = new javax.swing.JLabel();
        labelDado1 = new javax.swing.JLabel();
        btnTirarDados = new javax.swing.JToggleButton();
        scrollTablero = new javax.swing.JScrollPane();
        panelTablero = new javax.swing.JPanel();
        panelAccionesJugador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTempTitulo.setText("Tiempo del Juego");

        labelTemporizador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTemporizador.setText("00: 00: 00");

        btnPausarTemp.setText("Pausar");

        btnIniciarTemp.setText("Iniciar");

        horas.setText("horas");

        jLabel2.setText("minutos");

        btnTirarDados.setText("Tirar dados");
        btnTirarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTirarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(778, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(labelDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelDado3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(btnTirarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIniciarTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPausarTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horas)
                            .addComponent(spinerHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(spinerMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelTempTitulo)
                    .addComponent(labelTemporizador, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTempTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(horas)
                            .addComponent(btnPausarTemp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinerMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinerHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIniciarTemp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTemporizador, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDado3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTirarDados)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1229, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        scrollTablero.setViewportView(panelTablero);

        panelAccionesJugador.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout panelAccionesJugadorLayout = new javax.swing.GroupLayout(panelAccionesJugador);
        panelAccionesJugador.setLayout(panelAccionesJugadorLayout);
        panelAccionesJugadorLayout.setHorizontalGroup(
            panelAccionesJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        panelAccionesJugadorLayout.setVerticalGroup(
            panelAccionesJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAccionesJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTablero, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(panelAccionesJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTirarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTirarDadosActionPerformed
        int n = 3;
        JLabel[] labels = new JLabel[3];
        labels[0] = labelDado1;
        labels[1] = labelDado2;
        labels[2] = labelDado3;
      

        for (int i = 0; i < n; i++) {
            //se crean los hilos para cada dado y se le da inicio
            Thread d1 = new Thread(new ManejadorDado(labels[i]));
            d1.start();

        }

    }//GEN-LAST:event_btnTirarDadosActionPerformed

    @Override
    public void actionPerformed(ActionEvent e) {
        int hora = (int) spinerHoras.getValue();
        int minuto = (int) spinerMinutos.getValue();
        if (e.getSource() == btnIniciarTemp) {
            iniciarHiloTemporizador(hora, minuto);
            if (corriendoTemp == false) {
                iniciarTarea = true;
                corriendoTemp = true;

            }
        }
        if (e.getSource().equals(btnPausarTemp)) {
            corriendoTemp = false;
            iniciarTarea = false;
        }
    }

    public void iniciarHiloTemporizador(int hora, int minuto) {
        if (iniciarTarea == true) {
            temporizador = new Temporizador(labelTemporizador, hora, minuto);
            //se realiza el proceso cada segundo
            temporizador.iniciandoTemporizador(0, 100);

        }
    }

    public void agregarCasillas() {
        //Se obtiene lac cantidad que contienen los espiner asignando a filas y columnas respectivamente
        int dimension = 75, columnas = 18, filas = 18;
        CasillaUI[][] casillasUi = new CasillaUI[10][10];
        CasillaUI casillaUi = new CasillaUI();
        //Eliminamos los anteriores botones
        panelTablero.removeAll();
        panelTablero.setSize(dimension * columnas, dimension * filas);
        panelTablero.setPreferredSize(panelTablero.getSize());
        /*
        //Se crea una matriz de casillasUi segun las filas y columnas entrantes
        casillasUi = new CasillaUI[filas][columnas];
        
        //Se recorren las filas
        for (int fila = 0; fila < filas; fila++) {
            //Estando en la fila se recorrer las columnas
            for (int columna = 0; columna < columnas; columna++) {

                casillasUi[fila][columna] = new CasillaUI(dimension * columna, dimension * fila, dimension, dimension);
                casillasUi[fila][columna].addMouseMotionListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        System.out.println("probando");
                    }

                });

                panelTablero.add(casillasUi[fila][columna]);
            }
        }*/
        casillasUi[0][1] = new CasillaUI(dimension * 1, dimension * 0, dimension, dimension);
        casillasUi[0][1].getLabelNombreCasilla().setText("INICIO");
        casillasUi[0][1].getLabelNombreCasilla().setBackground(CasillaUI.getCOLOR2());
        casillasUi[9][2] = new CasillaUI(dimension * 2, dimension * 9, dimension, dimension);
        casillasUi[3][3] = new CasillaUI(dimension * 3, dimension * 3, dimension, dimension);
        casillasUi[4][8] = new CasillaUI(dimension * 8, dimension * 4, dimension, dimension);
        panelTablero.add(casillasUi[0][1]);
        panelTablero.add(casillasUi[9][2]);
        panelTablero.add(casillasUi[3][3]);
        panelTablero.add(casillasUi[4][8]);
        //Se actualiza el panel para que se vean los casillasUi
        panelTablero.updateUI();
        scrollTablero.validate();
        scrollTablero.repaint();
    }

    public void agregarIconoDados() {
        ImageIcon iconoDado1 = new ImageIcon("imagenes/11.jpg");
        labelDado1.setIcon(new ImageIcon(iconoDado1.getImage().getScaledInstance(labelDado1.getSize().width,
                labelDado1.getSize().height, Image.SCALE_SMOOTH)));
        ImageIcon iconoDado2 = new ImageIcon("imagenes/22.jpg");
        labelDado2.setIcon(new ImageIcon(iconoDado2.getImage().getScaledInstance(labelDado2.getSize().width,
                labelDado2.getSize().height, Image.SCALE_SMOOTH)));
        ImageIcon iconoDado3 = new ImageIcon("imagenes/33.jpg");
        labelDado3.setIcon(new ImageIcon(iconoDado3.getImage().getScaledInstance(labelDado2.getSize().width,
                labelDado3.getSize().height, Image.SCALE_SMOOTH)));

    }

    public boolean getIniciarHilo() {
        return iniciarTarea;
    }

    public boolean getCorriendoTemp() {
        return corriendoTemp;
    }

    public JSpinner getSpinerHoras() {
        return spinerHoras;
    }

    public JSpinner getSpinerMinutos() {
        return spinerMinutos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnIniciarTemp;
    public static javax.swing.JButton btnPausarTemp;
    private javax.swing.JToggleButton btnTirarDados;
    private javax.swing.JLabel horas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelDado1;
    private javax.swing.JLabel labelDado2;
    private javax.swing.JLabel labelDado3;
    private javax.swing.JLabel labelTempTitulo;
    private static javax.swing.JLabel labelTemporizador;
    private javax.swing.JPanel panelAccionesJugador;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelTablero;
    private javax.swing.JScrollPane scrollTablero;
    public javax.swing.JSpinner spinerHoras;
    public javax.swing.JSpinner spinerMinutos;
    // End of variables declaration//GEN-END:variables

}
